---

azerothcore_install_path: "/opt/azcore"

azerothcore_install_compose_repository: https://github.com/azerothcore/acore-docker.git
azerothcore_install_compose_version: fe1d9a8621e48406a3e19d1db4088326fa3b464c
azerothcore_install_compose_repository_path: "{{ azerothcore_install_path }}/acore-docker"

azerothcore_install_modules_path: "{{ azerothcore_install_path }}/modules"
azerothcore_install_config_path: "{{ azerothcore_install_path }}/configs"
azerothcore_install_assets_path: "{{ azerothcore_install_path }}/data"
azerothcore_install_scripts_path: "{{ azerothcore_install_path }}/scripts"

azerothcore_install_enable_soap: true
azerothcore_install_soap_port: "7878"

azerothcore_install_db_pwd: "{{ undef(hint='azerothcore_install_db_pwd needs a password defined to proceed') }}"
azerothcore_install_phpmyadmin_port: "8080"

azerothcore_install_environment:
  DOCKER_CLIENT_DATA_FOLDER: "{{ azerothcore_install_assets_path }}"
  DOCKER_DB_ROOT_PASSWORD: "{{ azerothcore_install_db_pwd }}"
  DOCKER_SOAP_EXTERNAL_PORT: "{{ azerothcore_install_soap_port }}"

azerothcore_install_default_tag: master
azerothcore_install_default_registry: docker.io
azerothcore_install_registry: >-
  {{
  azerothcore_build_registry_address
  if azerothcore_build_images | default(false) | bool
  else azerothcore_install_default_registry
  }}
azerothcore_install_tag: >-
  {{
  azerothcore_build_image_tag
  if azerothcore_build_images | default(false) | bool
  else azerothcore_install_default_tag
  }}

azerothcore_install_compose_overrides:
  services:
    ac-db-import:
      image: "{{ azerothcore_install_registry }}/acore/ac-wotlk-db-import:{{ azerothcore_install_tag }}"
    ac-worldserver:
      image: "{{ azerothcore_install_registry }}/acore/ac-wotlk-worldserver:{{ azerothcore_install_tag }}"
      volumes:
        - "{{ azerothcore_install_modules_path }}:/azerothcore/modules"
        - "{{ azerothcore_install_config_path }}/modules:/azerothcore/env/dist/etc/modules"
        - "{{ azerothcore_install_config_path }}/worldserver.conf:/azerothcore/env/dist/etc/worldserver.conf"
        - "{{ azerothcore_install_scripts_path }}/lua:/azerothcore/env/dist/bin/lua_scripts/scripts"
        - "${DOCKER_VOL_CLIENT_DATA:-ac-client-data}:/azerothcore/env/dist/data:ro"
    ac-authserver:
      image: "{{ azerothcore_install_registry }}/acore/ac-wotlk-authserver:{{ azerothcore_install_tag }}"
      volumes:
        - "{{ azerothcore_install_modules_path }}:/azerothcore/modules"
        - "{{ azerothcore_install_config_path }}/modules:/azerothcore/env/dist/etc/modules"
    ac-eluna-ts-dev:
      volumes:
        - "{{ azerothcore_install_scripts_path }}/typescript:/eluna-ts/modules"
        - "{{ azerothcore_install_scripts_path }}/lua:/eluna-ts/dist/"
      healthcheck:
        test: sh -c "cd /eluna-ts && npm run build:lib && npm run build"
    phpmyadmin:
      ports:
        - "{{ azerothcore_install_phpmyadmin_port }}:80"
