---

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ azerothcore_docker_project_path }}"
    - "{{ azerothcore_docker_modules_path }}"
    - "{{ azerothcore_docker_config_path }}"
  become: true

- name: Clone upstream repository
  ansible.builtin.git:
    repo: "{{ azerothcore_docker_repository }}"
    version: "{{ azerothcore_docker_repository_version }}"
    dest: "{{ azerothcore_docker_repository_path }}"
    force: true
  become: true

- name: Clone progression repository
  ansible.builtin.git:
    repo: "{{ azerothcore_docker_progression_repository }}"
    version: "{{ azerothcore_docker_progression_version }}"
    dest: "{{ azerothcore_docker_modules_path }}/mod-individual-progression"
  become: true

- name: Ensure config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ azerothcore_docker_config_path }}"
    - "{{ azerothcore_docker_config_path }}/modules"
  become: true

- name: Template worldserver config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/worldserver.conf"
    dest: "{{ azerothcore_docker_config_path }}/worldserver.conf"
    mode: "0644"
    unsafe_writes: true
  become: true

- name: Template module configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ azerothcore_docker_config_path }}/modules/{{ item | basename }}"
    unsafe_writes: true
  loop: "{{ lookup('ansible.builtin.fileglob', role_path ~ '/files/modules/*', wantlist=True) }}"
  become: true

- name: Slurp upstream compose file
  ansible.builtin.slurp:
    src: "{{ azerothcore_docker_project_path }}/docker-compose.yml"
  register: upstream_compose

- name: Merge overrides to upstream compose
  ansible.builtin.set_fact:
    azerothcore_docker_project_definition: >-
      {{ upstream_compose.content
        | b64decode
        | from_yaml
        | combine(
            azerothcore_docker_compose_overrides,
            recursive = True
              )
      }}

- name: Ensure scripts are copied to project directory
  ansible.builtin.copy:
    src: "{{ azerothcore_docker_repository_path }}/scripts"
    dest: "{{ azerothcore_docker_project_path }}/scripts"
  become: true

- name: Ensure compose is written
  ansible.builtin.copy:
    content: "{{ azerothcore_docker_project_definition | to_nice_yaml(indent=2) }}"
    dest: "{{ azerothcore_docker_project_path }}/docker-compose.yml"
  become: true
