---

- name: Ensure images are pushed
  ansible.builtin.shell: |
    docker tag acore/ac-wotlk-{{ item }}:{{ azerothcore_docker_image_tag }} {{ inventory_hostname }}:5000/acore/ac-wotlk-{{ item }}:{{ azerothcore_docker_image_tag }}
    docker push {{ inventory_hostname }}:5000/acore/ac-wotlk-{{ item }}:{{ azerothcore_docker_image_tag }}
  become: true
  environment:
    DOCKER_IMAGE_TAG: "{{ azerothcore_docker_image_tag }}"
  loop:
    - worldserver
    - authserver
    - db-import
