---

- name: Update realmlist
  ansible.mysql.mysql_query:
    login_host: "{{ azerothcore_install_db_address | default(ansible_facts.default_ipv4.address) }}"
    login_port: "{{ azerothcore_install_db_port | default('63306') }}"
    login_user: root
    login_password: "{{ azerothcore_install_db_pwd }}"
    login_db: acore_auth
    query: >-
      UPDATE realmlist
      SET name = %s, address = %s, localAddress = %s, port = %s
      WHERE id = 1
    positional_args:
      - "{{ azerothcore_realmlist_name }}"
      - "{{ azerothcore_realmlist_address }}"
      - "{{ azerothcore_realmlist_local_address }}"
      - "{{ azerothcore_realmlist_port }}"
