---

- name: Clone module repositories
  ansible.builtin.git:
    repo: "{{ item.value.repository }}"
    version: "{{ item.value.version }}"
    dest: "{{ azerothcore_install_modules_path }}/{{ item.key }}"
  loop: "{{ azerothcore_modules_dictionary | dict2items }}"
  become: true

- name: Ensure config directories exist
  ansible.builtin.file:
    path: "{{ azerothcore_install_config_path }}/modules"
    state: directory
  become: true

- name: Find role module config templates
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    patterns: "*.conf"
    file_type: file
  register: azerothcore_modules_role_config_templates
  delegate_to: localhost
  become: false

- name: Find user module config templates
  ansible.builtin.find:
    paths: "{{ inventory_dir | dirname }}/files/modules"
    patterns: "*.conf"
    file_type: file
  register: azerothcore_modules_user_config_templates
  delegate_to: localhost
  become: false

- name: Template module configs
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ azerothcore_install_config_path }}/modules/{{ item.path | basename }}"
  loop: >-
    {{
    azerothcore_modules_role_config_templates.files
    + azerothcore_modules_user_config_templates.files
    }}
  become: true

# NOTE(hollie): need to resolve permissions project wide.
- name: Fix module perms
  ansible.builtin.file:
    path: "{{ azerothcore_install_config_path }}/modules/"
    mode: "0777"
    state: "directory"
    recurse: true
  become: true
