---

- name: Clone builder repository
  ansible.builtin.git:
    repo: "{{ azerothcore_build_repository }}"
    version: "{{ azerothcore_build_version }}"
    dest: "{{ azerothcore_build_repository_path }}"
    force: true
  become: true

- name: Copy modules into builder directory
  ansible.builtin.copy:
    src: "{{ azerothcore_install_modules_path }}/{{ item.key }}"
    dest: "{{ azerothcore_build_repository_path }}/modules"
    remote_src: true
  become: true
  loop: "{{ azerothcore_modules_dictionary | dict2items }}"

- name: Slurp builder compose file
  ansible.builtin.slurp:
    src: "{{ azerothcore_build_repository_path }}/docker-compose.yml"
  register: azerothcore_build_compose

- name: Merge overrides to upstream compose
  ansible.builtin.set_fact:
    azerothcore_build_project_definition: >-
      {{ azerothcore_build_compose.content
      | b64decode
      | from_yaml
      | combine(
      azerothcore_build_compose_overrides,
      recursive = True
      )
      }}

- name: Ensure compose is written
  ansible.builtin.copy:
    content: "{{ azerothcore_build_project_definition | to_nice_yaml(indent=2) }}"
    dest: "{{ azerothcore_build_repository_path }}/docker-compose.yml"
  become: true
  register: azerothcore_build_compose_state

- name: Build custom AzerothCore images
  ansible.builtin.shell: |
    cd {{ azerothcore_build_repository_path }}
    docker compose build --no-cache {{ azerothcore_build_images_list | join(' ') }}
  become: true
  changed_when: "{{ azerothcore_build_compose_state.changed }}"
  environment:
    DOCKER_IMAGE_TAG: "{{ azerothcore_build_image_tag }}"

- name: Ensure images are pushed
  ansible.builtin.include_tasks: push-images.yml
  when: azerothcore_build_push_images
