---

- name: Build AzerothCore images
  hosts: azerothcore
  vars:
    azerothcore_build_images: true
  roles:
    - role: holliefae.azerothcore.azerothcore_install
    - role: holliefae.azerothcore.azerothcore_modules
    - role: holliefae.azerothcore.azerothcore_build
      when: azerothcore_build_images
