---

- name: Deploy AzerothCore
  hosts: azerothcore
  roles:
    - role: holliefae.azerothcore.azerothcore_install
    - role: holliefae.azerothcore.azerothcore_modules
    - role: holliefae.azerothcore.azerothcore_build
      when: azerothcore_build_images | default(true) | bool
  tasks:
    - name: Deploy AzerothCore compose
      community.docker.docker_compose_v2:
        project_src: "{{ azerothcore_install_path }}"
        state: "{{ azerothcore_deploy_state | default('present') }}"
        wait: true
      environment: "{{ azerothcore_install_environment }}"
      become: true
